package palsave

import (
	"context"
	"os/exec"
	"path/filepath"
	"testing"
)

// The fixture Level.sav is synthetic — generated by testdata/gen_fixture.py
// via palworld-save-tools' own JSON->SAV writer, so it exercises the real
// decompress/GVAS-parse/extract path without any copyrighted game data.
func TestReadFixture(t *testing.T) {
	if err := exec.Command("python3", "-c", "import palworld_save_tools").Run(); err != nil {
		t.Skip("python3 with palworld-save-tools not available")
	}

	reader, err := NewReader(t.TempDir())
	if err != nil {
		t.Fatal(err)
	}

	// Pass the directory: Read must resolve it to Level.sav inside.
	dir, err := filepath.Abs("testdata")
	if err != nil {
		t.Fatal(err)
	}
	result, err := reader.Read(context.Background(), dir)
	if err != nil {
		t.Fatal(err)
	}

	if len(result.Players) != 2 {
		t.Fatalf("want 2 players, got %d", len(result.Players))
	}
	kyoshi := result.Players[0]
	if kyoshi.Nickname != "Kyoshi" || kyoshi.Level != 42 {
		t.Fatalf("unexpected first player: %+v", kyoshi)
	}
	if len(kyoshi.Party) != 2 || len(kyoshi.Palbox) != 2 || len(kyoshi.Base) != 1 {
		t.Fatalf("kyoshi buckets wrong: party=%d palbox=%d base=%d",
			len(kyoshi.Party), len(kyoshi.Palbox), len(kyoshi.Base))
	}
	boss := kyoshi.Party[1]
	if boss.CharacterID != "BOSS_Anubis" || !boss.IsBoss || boss.TalentHP != 100 {
		t.Fatalf("unexpected boss pal: %+v", boss)
	}
	if !kyoshi.Palbox[1].IsLucky {
		t.Fatalf("Kitsunebi should be lucky: %+v", kyoshi.Palbox[1])
	}

	ren := result.Players[1]
	if ren.Nickname != "Ren" || len(ren.Party) != 1 || len(ren.Palbox) != 1 || len(ren.Base) != 0 {
		t.Fatalf("unexpected ren: %+v", ren)
	}

	// Second read must come from cache (same mtime) — verified by pointer
	// identity, since a re-parse would allocate a fresh Result.
	again, err := reader.Read(context.Background(), dir)
	if err != nil {
		t.Fatal(err)
	}
	if again != result {
		t.Fatal("expected cached result on unchanged mtime")
	}
}
